### ISSUE TITLE
Endless loop when no connection to Logz.io

### ISSUE THREAD

**Issue by 4OH4** [logzio/logzio-python-handler#68] opened 2022-01-19 15:46 UTC
I'm sending Python application logs to Logz.io. If there is not connection to the remote server, `logzio-python-handler` sits in an endless loop retrying until the queue is empty (which it never is because the logs never get sent because there is no connection).

Is this desirable behaviour? I would imagine that there should be a limit on the number of retries. My application essentially hangs when closing, as it is waiting for the logs handler to flush.

```
Got exception while sending logs to Logz.io, Try (4/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>>(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000214D43E8FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2022-01-19 15:45:01,623 - logzio.logger - WARNING - Got exception while sending logs to Logz.io, Try (4/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>>(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000214D43E8FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Could not send logs to Logz.io after 4 tries, backing up to local file system
2022-01-19 15:45:17,640 - logzio.logger - ERROR - Could not send logs to Logz.io after 4 tries, backing up to local file system
Backing up your logs to logzio-failures-19012022-154517.txt
2022-01-19 15:45:17,642 - logzio.logger - INFO - Backing up your logs to logzio-failures-19012022-154517.txt
Got exception while sending logs to Logz.io, Try (1/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>>(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000214D3DC4BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2022-01-19 15:45:19,741 - logzio.logger - WARNING - Got exception while sending logs to Logz.io, Try (1/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>>(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000214D3DC4BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

**Comment by 4OH4** [comment] 2022-01-19 17:20
The problem seems to arise because each time `sender.py` tries to drain the logs (and fails), it generates 4 new log messages (one from each of the retry attempts), then 2 new messages relating to log backup to file. It then tries to send the 6 new log messages, fails and generates 6 new log messages, and the cycle repeats.

I'm using the config from `README.md` - is there perhaps an alternate config that doesn't cause the logging handler errors to be sent alongside application errors?

```
Starting to drain 6 logs to Logz.io
Got exception while sending logs to Logz.io, Try (1/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Got exception while sending logs to Logz.io, Try (2/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Got exception while sending logs to Logz.io, Try (3/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Got exception while sending logs to Logz.io, Try (4/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Could not send logs to Logz.io after 4 tries, backing up to local file system
Starting to drain 6 logs to Logz.io
Got exception while sending logs to Logz.io, Try (1/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Got exception while sending logs to Logz.io, Try (2/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Got exception while sending logs to Logz.io, Try (3/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Got exception while sending logs to Logz.io, Try (4/4). Message: HTTPSConnectionPool(host='listener-nl.logz.io', port=8071): Max retries exceeded with url: /?token=<<mytoken>> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3DD5E1880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Could not send logs to Logz.io after 4 tries, backing up to local file system
```

**Comment by tamir-michaeli** [comment] 2022-01-19 23:24
@4OH4 What version are you using?

**Comment by 4OH4** [comment] 2022-01-20 11:06
> @4OH4 What version are you using?

Hi @tamir-michaeli - I'm seeing the above using a fresh install of `logzio-python-handler-3.1.0`

**Comment by rupertthomas** [comment] 2022-02-25 18:11
I believe the issue is arising because `logzio-python-handler` is creating log messages itself, when errors occur while handling other log messages. The are meant to be written just to `stdout`, but because the handler gets attached to the root logger it ends up handling all the log messages - including the ones it creates itself, causing the endless loop. Does that sound feasible?

If I replace the `stdout_logger` in `logger.py` with a mock logger that just prints messages, the problem goes away:

```python
class MockLogger:
    
    def debug(self, message, *args, **kwargs):
        self.print(message)
    
    def info(self, message, *args, **kwargs):
        self.print(message)
    
    def warning(self, message, *args, **kwargs):
        self.print(message)
    
    def error(self, message, *args, **kwargs):
        self.print(message)
    
    def critical(self, message, *args, **kwargs):
        self.print(message)

def get_stdout_logger(debug):
    # return __get_logger(debug, __name__ + '_stdout', logging.StreamHandler(sys.stdout))
    return MockLogger()
```

**Comment by tamir-michaeli** [comment] 2022-02-27 08:05
@rupertthomas Yes this is where the issue is, this is fixed by setting the propagate option to False for the std_out logger . A new version will be release in the next few days (with additional fixes) :).

**Closed** 2022-03-06 12:37 UTC
